### ISSUE TITLE
Add web browser

### ISSUE THREAD

**Issue by p4trykx** [xbianonpi/xbian#167]
Would it be possible to add a web browser to Xbian. There is a lightweight NetSurf. It lacks Javascript but is reasonably fast comparing to Midori or Chorme. I think it can also run without X server.

**Comment by ziirish** [comment]
Hi,

I answered on the [forum](http://forum.xbian.org/thread-79-post-34519.html#pid34519) as well, but [here](https://gist.github.com/ziirish/4b92d9b48ef203b6fcfcfeb2f7e95a6d) is how I managed to launch a web browser (firefox) on Xbian.

You can surely run whatever browser you like, just edit the `/home/xbian/.xsession` file.

**Comment by inspector71** [comment]
Wow, so many years between updates!

In the interim - and yeah, it took around 5 years *sigh* - the RasFo has moved from the (unfortunately) awful Gecko-based clones to prioritising Chromium which now has _some_ (I'm not sure how much) hardware acceleration on the Pi. A browser without hardware acceleration these days is quite a limited beast. Any browser on the Raspberry Pi, with it's very minimal RAM, without hardware acceleration, may be usable on lo-fi sites. On most of the more popular sites, and sadly too many of your garden variety sites, the bloat would be somewhat challenging for browsers on the pi without hardware acceleration. Even with hardware acceleration, any site with significant embedded content such as videos or fancy graphical effects (now most commonly delightfully applied with HTML5 instead of presenting yet another ballache for platforms: Flash plugins) would probably not be a rapid experience but one that requires more patience than other platforms. Eben Upton said the RasFo was targeting Chromium with a decent YouTube experience on the Pixel desktop. That would mean h264 video acceleration support for browsers. As the only browser they are targeting is WebShit/Blink-based, and Mozilla is in a massive cut-and-run phase with Firefox/Gecko/e10s/Servo/WebExtensions and so forth, running anything but Chromium on a platform already using resources to run Kodi in the background (behind/underneath the browser) would be a dubious experience in the context of today's multi-tab browsing we're often familiar with. Single tab-at-a-time, mostly text pages? Maybe. If that's your use case, I hope you enjoy it :)

FWIW, I use LibreELEC these days.

**Comment by ziirish** [comment]
Of course it's not as fast as on your thousands dollars desktop. But I can do multi-tab, and browse my most common websites and even more without much problems. It's not meant to play YouTube videos although it's doable. For this you can/should use Kodi, and guess what? That's what Xbian is meant for. You just have to exit the browser to get back to Kodi.You can also edit the script to run whatever browser you like. I tried midori but it requires some extra tricks so I stick with Firefox.If you read my message, I said kodi *must* be exited for the script to launch your browser. It means both cannot and *shouldn't* run at the same time. I'm not as dumb as you think smart kid.Now I posted my solution mostly because during my searching I ended up here and I guess I'm not the only one looking for such a trick.
