### ISSUE TITLE
CEC not automatically connecting after upgrading to staging

### ISSUE THREAD

**Issue by hackedbellini** [xbianonpi/xbian#495]
Hi,

When on stable, I just needed to connect CEC once (using LG's simplink) and then, turning off the TV and turning it on again would automatically connect again.

I upgraded to staging a week ago (and thus, xbian-package-cec was updated), and since them, every time I turn of the TV and turn it on, I have to connect CEC again.

It's a very minor issue, since it's just pressing a button to make it connect, but it's a regression since it used to do that automatically.

**Comment by hackedbellini** [comment]
As @mk01 asked me, here is a quick update:

I'm using the latest version released, ```xbian-packae-cec=9.2.2.0-1-1416753800``` and helix from ```xbian-package-xbmc-nightly=14.1~RC1-1419732896```.

I think nothing has changed from this issue's point of view. As it was before, CEC is working great in all scenarios, except one: When I turn the TV off for more than a minute (not exactly that), when I turn it on again and move to xbian's source, I need to reconnect it.

Other than that, I can change sources, I can even restart my raspberry and it will automatically reconnect and work without any other problems.

So, it's a very minor issue, but still there =P

**Comment by hackedbellini** [comment]
Btw, I was using nightly for some tests, but changed back to ```xbian-package-xbmc=14.0-1419995228``` from devel for the resolution fix from (https://github.com/xbianonpi/xbian/issues/648). The results are the same though.

**Comment by opdenkamp** [comment]
sorry, but i have no idea what versions of xbmc and libCEC were used in those packages.
please try to reproduce the issue, and pastebin xbmc's debug log.

**Comment by hackedbellini** [comment]
@opdenkamp here is the log: http://paste.debian.net/139020/

I did the same as the previous tests (you can see old logs I sent in the thread).

1) Started the raspberry and pressed some buttons. CEC was working ok
2) Changed the source to my hdmi cable tv and turned the tv off (around 09:09)
3) Turned the tv on and changed the source to the raspberry (around 09:11)
4) Needed to manually reconnect CEC so I could send some key presses

Please tell me if you need more info.

**Comment by mk01** [comment]
@hackedbellini 

with Helix you have to (even if --debug on command line) enable DEBUG logging for specific subsystems - cec in this case (under xbmc->settings->system.... )

@opdenkamp - the specific versions of libCec discussed were:
2.1.3 - action (described one post up) was ok
2.1.4 - no ok
2.2.0 - no ok

this bug is relevant only to LG handler (SLCommandHandler.cpp) and some of the code in e8fca5f85246f85685c814dc213f0b152295a318, 5d71f08c3211791a51f6d7b0bde3d41f2e56d71f and 34232c9249859abed3ae97c4d4289dd6ec87a2f6 . "SL" state is reset upon TV going standby, later never re-initialised (libCEC is trying to reinitialise, but TV answers with "feature abort" each single message).

**Comment by opdenkamp** [comment]
the log is useless indeed unfortunately. you may blame the release managers of helix for the logging craziness, and i'm not going to support debugging it because they've ignored my objections against it as maintainer of that code. it's been reverted back to a sane state in the master branch (nightly builds)

**Comment by jwamsterdam** [comment]
@hackedbellini Do you have any idea if this issue is fixed right now? It worked in the past, then it was broken by an LibCEC update, but MK11 did make a fix for it. Unfortunately that fix was lost in time, but I would really like to switch back from OpenElec to Xbian again.. Thnx for the update.

**Comment by hackedbellini** [comment]
@jwamsterdam not yet, although the issue is just that, after turning the tv off and on again, when changing sources to xbian, I need to ask it to reconnect to cec. After that everything works fine. So, it is not something that I care to workaround every time (2 button presses to do that =P)
