### ISSUE TITLE
Today's updates (xbian-update and xbian-sources-xbmc and xbian-package-xbmc) broke something

### ISSUE THREAD

**Issue by Smultie** [xbianonpi/xbian#711]
Kodi doesn't start at bootup and the /home directory is empty

Whenever I login with SSH:

*Last login: Tue Apr  7 15:14:48 2015 from 10.0.1.4*
*Could not chdir to home directory /home/xbian: No such file or directory*
*xbian@xbian / $*

And on the TV-screen it says:
*xbian login: [....] Setting preliminary keymap...rpcbind: cannot create socket for udp6*
*rpcbind: cannot create socket for udp6*
*udevd[678]: error opening ATTR{/sys/devices/platform/mmc-bcm2835.0/mmc_host/mmc0/mmc0:0001/block/mmcblk0/queue/ioschedule/target_latency} for writing: Permission Denied*

*done.*
*[ ok ] Setting up X socket directories... /tmp/.X11-unix /tmp/ .ICE-unix.*

**Comment by Smultie** [comment]
Narrowed it down to xbian-update 20150407-1
All the other updates work fine.

**Comment by mk01** [comment]
see my comment in that issue

**Comment by thomasbishop** [comment]
Same problem here. Applied today's update via the SSH menu, rebooted and... it fails with the same error message as @Smultie is seeing.

@mk01 I can't answer your question in the other thread as I can't get in via SSH (my Pi is wireless only, I guess the boot sequence is failing before the wireless connection is initialised) but I've never manually set anything on the Pi... I did a clean installation when the Pi v2 arrived, then applied every update through the SSH menu. No manual changes to config files, no installations via apt-get etc. Just a 'vanilla' configuration! Hope that helps.

**Comment by mk01** [comment]
@thomasbishop 

sorry for the break. I removed that particular xbian-update from apt already - hopefully you are just few users who managed to process that update almost instantly. 

indeed that info helped and I have the feeling it will be ok with the fixed package (already released). just need it to get confirmed from you (once you manage to get to your RPI) and @Smultie. 

@Smultie will just reinstall xbian-update because his PRI manage to start with network, ... you will have to remove /etc/default/tmpfs file (if my theory is correct), then reboot, ... then your RPI should boot correctly, then try the last xbian-update. it should be ok after this update.

I have the feeling the problem with /home mounting (or even bigger with you) wasn't caused directly by the new code - and being dormant, but with wrong /etc/default/tmpfs file update -> some parts updated to garbage (as @mkreisl said earlier). 

mount/mountall is reading this file and that's the moment when it probably due to the garbage collapses (whole boot in your case, "only" incorrect mounting for @Smultie)).

once you guys recover and retest, report please back.

**Comment by thomasbishop** [comment]
OK, thanks - I'll try that. I just tried booting with keyboard plugged in but the system is completely frozen after the line:

    [ ok ] Setting up X socket directories... /tmp/.X11-unix /tmp/ .ICE-unix.

so I'll need to pull the SD card and open it on another computer to delete the `tmpfs` file. Will report back asap.

**Comment by mk01** [comment]
uncomment initramfs.gz line in /boot/config.txt to have boot with initramfs (or if it is booting like that) - just hold left shift on keyboard. you will get recovery shell right away. with some short howto.

**Comment by mk01** [comment]
@thomasbishop 
you won't mount the root of another (not patched accordingly) kernel.

still, to save you from panic and reflash - edit cmdline.txt on the 1st fat partition, put keyword "rescue" and save, edit config.txt and uncomment "initramfs.gz" line. 

you will get recovery shell (with rootfs mounted under /rootfs/). so delete 
```
rm /rootfs/etc/default/tmpfs
reb
```

(reb instead of reboot is correct)

**Comment by Smultie** [comment]
Your comments didn't work @mk01 
After doing what you told, still no Kodi and no home-folder.

**Comment by tom4242** [comment]
I have the same problems and think that it is a general problem with an updated package for the pi 2.
i tried the stable release and also the relase of 2015.04.04. after an apt-get update & upgrade and a reboot xbian stopped working. Error message described at the top from Smultie . Very strange.

**Comment by mk01** [comment]
@Smultie 

and if you revert to xbian-update last before april ? 20150304-2

apt-get install xbian-update=20150304-2

?

**Comment by Smultie** [comment]
No problem with all xbian-update version before 20150307-1.
So only problems with 20150307-1 and 20150308-0.

**Comment by agijsberts** [comment]
I ran into the same error reported by thomasbishop when I update to 20150408-0 (either via 20150407-0 or directly from an earlier bcakup). Pinning xbian-update to version 20150304-2 and all is ok again.

Before getting stuck at the (unrelated?) [i]X socket directories[/i] message it is displaying the [i]Loading[/i] splash screen for an unusually long time.

**Comment by The-Exnor** [comment]
Same problem here... fortunately i only updated 1 of my units....

**Comment by mkreisl** [comment]
Hmm, why do I have no problems with 20150307-1 and 20150308-0 ?
Tested on my 2 PIs, no issue

**Comment by Smultie** [comment]
@mkreisl what RPi version do you have? I have an RPi 2.

**Comment by agijsberts** [comment]
I have an RPi 1 model B instead.

**Comment by mkreisl** [comment]
@Smultie 
2x RPi 1B

**Comment by er0l** [comment]
rpi2 narrowed down the issue back to update 20150407-1

**Comment by kataclank** [comment]
same problem with my rpi b

**Comment by Lexmark0381** [comment]
Same here, RPI2.
Even cable-connection is giving troubles...

**Comment by kataclank** [comment]
sudo apt-get install xbian-update=20150304-2 Fix it and everything works fine now

**Comment by Smultie** [comment]
sudo apt-get install xbian-update=20150407-0 works fine too

**Comment by er0l** [comment]
I can confirm apt-get install xbian-update=20150407-0 works on my rpi2 too.

**Comment by CurlyMoo** [comment]
I've removed `20150408-0` and see that `20150407-0` was removed earlier by another dev. That should at least fix the spread of the issue to more users.

**Comment by Smultie** [comment]
If I'm current, only 20150407-1 was removed.

http://apt.xbian.org/pool/stable/main/x/xbian-update/

20150407-0 is still on there.

**Comment by CurlyMoo** [comment]
I updated my post. `20150407-0` was wrongly named on the server so i couldn't find it.

**Comment by dams1911** [comment]
Hello, I had the same problem yesterday and I've reinstalled my Pi2... (didn't know I could just downgrade to fix it).

Can I turn the auto update ON again now or should I wait ?

**Comment by The-Exnor** [comment]
@CurlyMoo just reinstalled the OS (again) an hour ago, updated (minus xbian-package-xbmc because of the reasons on the other thread) and so far no problems.

**Comment by m-urban** [comment]
Hi there,
I was running into the same issue yesterday with my RPi 1 B+. Running "apt-get install xbian-update=20150304-2" fixed it (thank you, @mk01!).

**Comment by xiolo** [comment]
20150407-0 works, but the list of local installed packages (nzbget etc..) si empty.

**Comment by xiolo** [comment]
also 20150407-0 on rpi2 doesn't allow for additional packages to be installed, as it brakes dependencies (libc6 error?).
Has to flash back to 20150304-2, install all updates except xbian-update-20150407-0, and the packages are then fine.

Moral of the story from my side on an RPI2: 20150304-2 is fine, 20150407-0 has broken packages list/installation.

**Comment by xiolo** [comment]
update on this. I restored a previous 20150304-2 backup, and carefully did an apt-get update/apt-get upgrade, and now running 20150407-0 on the pi2 with the list of packages all in order...

So unsure what was my previous issue (dodgy file/fs?).

Still getting a kernel panic/freeze every few days, so me thinking that 3.18 kernel (especially around the ethernet driver) is still a bit unstable :-)

**Comment by mk01** [comment]
@xiolo 

xbian-update itself didn't change own dependencies for a while so you are right it was "something in the clouds". 

@all

returning back to original topic - I would like to deploy the code (changed xbian-run.conf). as I can't replicate the issue on mine boxes, I would need someone who original had problem with the mentioned xbian-update and can provide remote access (so I would ssh in the box). 
that also means that the test subject's "broken" system should be like @Smultie's. no /home mounted, xbmc not starting (due to /home), but ssh works - so I would see untouched system after reboot. 

if nobody goes voluntarily, I will go one by one without asking :D

**Comment by Smultie** [comment]
@mk01 I can test for you, no problem.

**Comment by Lexmark0381** [comment]
@mk01 Sorry man, i made a clean installation after that bug..

**Comment by mk01** [comment]
@Smultie 

this time no "test for me" ... I  would need to see it myself (so I need logging in).

**Comment by Smultie** [comment]
Okay. I can provide you access

**Comment by mk01** [comment]
tell me a approx timing when you could loose maybe 1h doing anything but RPI.
and
I would send you deb. you dpkg -i , reboot... and provide access credentials. so ~10min, then I won't need you.
(we do snap before and rollback after so as I logout, you have your system back)

**Comment by Smultie** [comment]
Now would be fine
Can you come to IRC?

**Comment by B0rax** [comment]
>also 20150407-0 on rpi2 doesn't allow for additional packages to be installed, as it brakes dependencies (libc6 error?).
Has to flash back to 20150304-2, install all updates except xbian-update-20150407-0, and the packages are then fine.

how did you flash back? I'm on 20150407-0 on rpi2 and can't install anything (even the old updates), I'm quite stuck as it is now. I'm unable to physically access the SD card, so I would really prefer a solution over ssh (or directly via keyboard). Can anyone help me with this?
