### ISSUE TITLE
libcec3 is not removed when libcec4 is installed

### ISSUE THREAD

**Issue by ssakatausa** [xbianonpi/xbian#838]
I have just noticed that both libcec3 and libcec4 are installed on my RPi3. Isn't libcec4 supposed to replace libcec3? The versions of libcec3 and libcec4 installed on my machine are respectively

  3.1.0.1~xbian-14628598
  4.0.2.1~xbian-14889991

Best,

  S

**Comment by mkreisl** [comment]
That's right, libcec3 is not removed when libcec4 is being installed, but this does not matter because of different .so files. You can remove libcec3 manually.
Due to an minor issue in package list when building image libcec3 and libcec4 were both installed. This has been fixed at March 7, see this commit https://github.com/xbianonpi/xbian/commit/ba1003aa312a37397ec44c7ea69f0d33ca70aa04

**Comment by ssakatausa** [comment]
Thanks for your reply. I now see what is going on.
